#' Plot desirability scores
#'
#' This function plots genes with the top overall desirability scores and,
#' optionally, their desirability scores from all integrated data.
#'
#' @details By plotting genes with the top overall desirability scores as well
#' as their individual desirability scores from integrated data, the user can
#' visualize not only the most desirable candidates, but also where the
#' desirability signal is coming from within their data.
#' @param x A data matrix where the first column is overall desirability and
#' additional columns are desirability scores from individual tests.
#' @return Returns a geom_point plot generated by ggplot.
#' @export

desire_plot <- function(x, plot_type = plot.type){

  # Set plot type
  plot.type <- c("overall", "o", "top", "t")
  if(!hasArg(plot_type))
    stop("\nplot_type should be one of the following: 'overall' or 'top'\n\nfor more details see help page ?desire()")
  if(!is.element(plot_type, plot.type))
    stop("\nplot_type should be one of the following: 'overall' or 'top'\n\nfor more details see help page ?desire()")
  if(plot_type == "overall") plot_type <- "o"
  if(plot_type == "top") desire_type <- "t"

  # Sort data by overall desirability score
  dat <- x[rev(order(x[,2])),]

  # Plot all genes and their overall desirability scores
  if (plot_type == "o") {
    p1 <- ggplot() +
      geom_point(aes(x = seq(length(dat[,2])),
                     y = dat[,2]),
                 size = 2,
                 color = "black",
                 alpha = 0.5) +
      labs(x = "Rank",
           y = "Overall Desirability Score") +
      scale_y_continuous(limits = c(0, 1), breaks=seq(0, 1, 0.1)) +
      theme_classic()

    grid.arrange(p1)

  }

  # Plot top genes as well as their overall and individual desirability scores
  if (plot_type == "t") {
    # Plot top genes by overall desirability
    p2 <- ggplot() +
      geom_point(
        aes(
          x = seq(1,10,1),
          y = dat[1:10,2]),
        size = 5,
        color = "black",
        alpha = 1) +
      scale_x_continuous(
        breaks = 1:10, labels = c(
          paste('1\n', dat[1,1]),
          paste('2\n', dat[2,1]),
          paste('3\n', dat[3,1]),
          paste('4\n', dat[4,1]),
          paste('5\n', dat[5,1]),
          paste('6\n', dat[6,1]),
          paste('7\n', dat[7,1]),
          paste('8\n', dat[8,1]),
          paste('9\n', dat[9,1]),
          paste('10\n', dat[10,1]))) +
      labs(x = "Overall Desirability Rank", y = "Overall Desirability Score") +
      theme_classic()

    # Reformat data to represent data type instead of study
    top <- dat[1:10,]

    top.melt <- melt(top[,-2],
                     id.vars = c("Gene"),
                     value.name = c("Desirability"),
                     variable.name = c("Type"))

    top.melt[2] <- gsub(".*\\((.*)\\).*", "\\1", top.melt[,2])

    p3 <- ggplot() +
      geom_point(
        aes(
          x = rep(seq(1,length(top[,1]),1),length(top)-2),
          y = top.melt[,3],
          colour = top.melt$Type),
        size=3,
        alpha=0.75) +
      scale_x_continuous(
        breaks = 1:10, labels = c(
          paste('1\n', top.melt[1,1]),
          paste('2\n', top.melt[2,1]),
          paste('3\n', top.melt[3,1]),
          paste('4\n', top.melt[4,1]),
          paste('5\n', top.melt[5,1]),
          paste('6\n', top.melt[6,1]),
          paste('7\n', top.melt[7,1]),
          paste('8\n', top.melt[8,1]),
          paste('9\n', top.melt[9,1]),
          paste('10\n', top.melt[10,1]))) +
      labs(x = "Overall Desirability Rank", y = "Overall Desirability Score") +
      theme_classic() +
      theme(legend.position="right") +
      scale_colour_brewer(name = "Data Type", type = "qual", palette = "Paired", direction = 1)

    # Plot ranks from individual desirability scores
    dat[,3:length(dat)] <- lapply(-dat[,3:length(dat)],
                                  rank,
                                  ties.method = 'min')

    # Calculate number of unique ranks in each study
    nums <- c()
    for (i in seq(length(dat))) {
      nums[i] <- length(unique(dat[[i]]))
    }

    # Normalize ranks by number of unique ranks in each study
    dat <- dat[1:10,]
    dat[,3:length(dat)] <- sweep(dat[,3:length(dat)],2,nums[3:length(dat)],"/")
    dat.melt <- melt(dat[,-2],
                     id.vars = c("Gene"),
                     value.name = c("Individual Rank"),
                     variable.name = c("Data"))

    # Custom reverse log scale for y-axis
    reverselog_trans <- function(base = exp(1)) {
      trans <- function(x) -log(x, base)
      inv <- function(x) base^(-x)
      trans_new(paste0("reverselog-", format(base)), trans, inv,
                log_breaks(base = base),
                domain = c(1e-100, Inf))
    }

    p4 <- ggplot() +
      geom_point(data = dat.melt,
                 position=position_dodge(width = .6),
        aes(
          x = rep(seq(1,length(dat[,1]),1),length(dat)-2),
          y = dat.melt[,3],
          colour = dat.melt$Data),
        size = 2,
        alpha = 1,
        inherit.aes=FALSE) +
      scale_x_continuous(
        breaks = 1:10, labels = c(
          paste('1\n', dat.melt[1,1]),
          paste('2\n', dat.melt[2,1]),
          paste('3\n', dat.melt[3,1]),
          paste('4\n', dat.melt[4,1]),
          paste('5\n', dat.melt[5,1]),
          paste('6\n', dat.melt[6,1]),
          paste('7\n', dat.melt[7,1]),
          paste('8\n', dat.melt[8,1]),
          paste('9\n', dat.melt[9,1]),
          paste('10\n', dat.melt[10,1]))) +
      labs(x = "Overall Desirability Rank", y = "Relative Individual Rank (log10)") +
      theme_classic() +
      theme(legend.position="right") +
      scale_colour_brewer(name = "Study", type = "qual", palette = "Paired", direction = 1) +
      scale_y_continuous(trans=reverselog_trans(10), breaks = c(0, 0.0005, 0.01, 1))

    grid.arrange(p2, p3, p4, ncol = 1)

  }

}
