#' Plot desirability scores
#'
#' This function plots genes with the top overall desirability scores and,
#' optionally, their desirability scores from all integrated data.
#'
#' @details By plotting genes with the top overall desirability scores as well
#' as their individual desirability scores from integrated data, the user can
#' visualize not only the most desirable candidates, but also where the
#' desirability signal is coming from within their data.
#' @param x A data matrix where the first column is overall desirability and
#' additional columns are desirability scores from individual tests.
#' @return Returns a geom_point plot generated by ggplot.
#' @export

desire_plot <- function(x){

  p5 <- ggplot() +
    geom_point(aes(x = seq(from = 1, to = 1500),
                   y = data.All$D[1:1500]),
               size = 3,
               color = "#A2C669",
               alpha = 1) +
    labs(x = "Rank",
         y = "Overall Desirability") +
    scale_y_continuous(breaks = seq(0, 0.2, length = 11)) +
    geom_label(aes(x = seq(1:2),
                   y = data.All$D[1:2]),
               label=data.All$Gene[1:2],
               fill = "white",
               label.size=0,
               size=5,
               fontface=2,
               hjust=-0.1,
               vjust=0.5)

  grid.arrange(p5 + theme_classic(), ncol=1)

}
